version: '3.8'
services:
  db:
    image: postgres:latest
    hostname: db-sbf
    container_name: db-sbf
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=spring_user
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spring_user -d orderdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  order-service:
    image: order-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=spring_user
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
  relay1:
    image: message-relay:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=spring_user
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
  relay2:
    image: message-relay:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=spring_user
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka-sbf
    container_name: kafka-sbf
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper-sbf
    container_name: zookeeper-sbf
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
volumes:
  pgdata: